package quiz

import (
	"context"
	"fmt"
	"math/rand"
	"time"

	"github.com/akramboussanni/gocode/internal/model"
	"github.com/akramboussanni/gocode/internal/repo"
	"github.com/akramboussanni/gocode/internal/utils"
)

// AnswerGenerator handles automatic generation of wrong answers for MCQ
type AnswerGenerator struct {
	repos              *repo.Repos
	dataSourceRegistry *DataSourceRegistry
}

// NewAnswerGenerator creates a new answer generator
func NewAnswerGenerator(repos *repo.Repos, registry *DataSourceRegistry) *AnswerGenerator {
	return &AnswerGenerator{
		repos:              repos,
		dataSourceRegistry: registry,
	}
}

// GenerationConfig specifies how to generate wrong answers
type GenerationConfig struct {
	Count          int                    // Number of wrong answers to generate
	Rule           string                 // "same_category", "same_deck", "random", etc.
	DataSourceName string                 // Which data source to use
	Filters        map[string]interface{} // Additional filters for the data source
}

// GenerateWrongAnswers creates wrong answer options for a question
func (g *AnswerGenerator) GenerateWrongAnswers(ctx context.Context, question *model.Question, config GenerationConfig) ([]*model.AnswerOption, error) {
	// Get the appropriate data source
	dataSource, ok := g.dataSourceRegistry.Get(config.DataSourceName)
	if !ok {
		return nil, fmt.Errorf("data source '%s' not found", config.DataSourceName)
	}

	// Build filters based on generation rule
	filters := g.buildFilters(question, config)

	// Get random answers from the data source
	answers, err := dataSource.GetRandomAnswers(ctx, question.ID, config.Count, filters)
	if err != nil {
		return nil, fmt.Errorf("failed to get random answers: %w", err)
	}

	// If we don't have enough answers, try with less restrictive filters
	if len(answers) < config.Count {
		// Try with just deck filter
		fallbackFilters := map[string]interface{}{
			"deck_id": question.DeckID,
		}
		additionalAnswers, err := dataSource.GetRandomAnswers(ctx, question.ID, config.Count-len(answers), fallbackFilters)
		if err == nil {
			answers = append(answers, additionalAnswers...)
		}
	}

	// Create answer option models
	options := make([]*model.AnswerOption, 0, len(answers))
	now := time.Now().Unix()

	for i, answer := range answers {
		if answer == question.CorrectAnswer {
			// Skip if by chance we got the correct answer
			continue
		}

		option := &model.AnswerOption{
			ID:              utils.GenerateSnowflakeID(),
			QuestionID:      question.ID,
			OptionText:      answer,
			IsCorrect:       false,
			IsAutoGenerated: true,
			GenerationRule:  config.Rule,
			DisplayOrder:    i + 2, // Start from 2 (correct answer is usually 1)
			CreatedAt:       now,
		}
		options = append(options, option)
	}

	return options, nil
}

// buildFilters creates filter map based on generation rule and question context
func (g *AnswerGenerator) buildFilters(question *model.Question, config GenerationConfig) map[string]interface{} {
	filters := make(map[string]interface{})

	// Copy any custom filters
	for k, v := range config.Filters {
		filters[k] = v
	}

	// Apply rule-based filters
	switch config.Rule {
	case "same_category":
		filters["category_id"] = question.CategoryID
	case "same_deck":
		filters["deck_id"] = question.DeckID
	case "different_category":
		filters["deck_id"] = question.DeckID
		filters["exclude_category"] = question.CategoryID
	case "random":
		// No specific filters, get from anywhere
	default:
		// Default to same deck
		filters["deck_id"] = question.DeckID
	}

	return filters
}

// GenerateAndSaveOptions generates wrong answers and saves them with the correct answer
func (g *AnswerGenerator) GenerateAndSaveOptions(ctx context.Context, question *model.Question, config GenerationConfig) error {
	// Generate wrong answers
	wrongOptions, err := g.GenerateWrongAnswers(ctx, question, config)
	if err != nil {
		return err
	}

	// Create the correct answer option
	correctOption := &model.AnswerOption{
		ID:              utils.GenerateSnowflakeID(),
		QuestionID:      question.ID,
		OptionText:      question.CorrectAnswer,
		IsCorrect:       true,
		IsAutoGenerated: false,
		GenerationRule:  "",
		DisplayOrder:    1,
		CreatedAt:       time.Now().Unix(),
	}

	// Combine all options
	allOptions := append([]*model.AnswerOption{correctOption}, wrongOptions...)

	// Shuffle options if needed
	g.shuffleOptions(allOptions)

	// Update display order after shuffle
	for i, opt := range allOptions {
		opt.DisplayOrder = i + 1
	}

	// Save all options
	for _, opt := range allOptions {
		if err := g.repos.QuestionOption.Create(ctx, opt); err != nil {
			return fmt.Errorf("failed to save option: %w", err)
		}
	}

	return nil
}

// shuffleOptions randomly shuffles answer options
func (g *AnswerGenerator) shuffleOptions(options []*model.AnswerOption) {
	r := rand.New(rand.NewSource(time.Now().UnixNano()))
	r.Shuffle(len(options), func(i, j int) {
		options[i], options[j] = options[j], options[i]
	})
}

// CreateManualOptions creates manually specified answer options
func (g *AnswerGenerator) CreateManualOptions(ctx context.Context, question *model.Question, wrongAnswers []string) error {
	now := time.Now().Unix()

	// Create correct answer option
	correctOption := &model.AnswerOption{
		ID:              utils.GenerateSnowflakeID(),
		QuestionID:      question.ID,
		OptionText:      question.CorrectAnswer,
		IsCorrect:       true,
		IsAutoGenerated: false,
		DisplayOrder:    1,
		CreatedAt:       now,
	}

	if err := g.repos.QuestionOption.Create(ctx, correctOption); err != nil {
		return fmt.Errorf("failed to create correct option: %w", err)
	}

	// Create wrong answer options
	for i, answer := range wrongAnswers {
		option := &model.AnswerOption{
			ID:              utils.GenerateSnowflakeID(),
			QuestionID:      question.ID,
			OptionText:      answer,
			IsCorrect:       false,
			IsAutoGenerated: false,
			DisplayOrder:    i + 2,
			CreatedAt:       now,
		}

		if err := g.repos.QuestionOption.Create(ctx, option); err != nil {
			return fmt.Errorf("failed to create wrong option: %w", err)
		}
	}

	return nil
}
